[annotator] Add CaddIndel -> VCF script (#340)
* Adds script to convert CaddIndel format, which is something they came
up with, for VCF, which is standard. This allows us to re-use our VCF
builder to build CaddIndel scores.

Input:
```
## CADD GRCh37-v1.6 (c) University of Washington, Hudson-Alpha Institute for Biotechnology and Berlin Institute of Health 2013-2020. All rights reserved.
#Chrom  Pos     Ref     Alt     RawScore        PHRED
1       10001   T       TC      -0.115832       1.266
1       10009   A       AC      -0.115586       1.268
1       10012   C       CT      -0.116324       1.261
1       10013   T       TA      -0.116117       1.263
1       10015   A       AC      -0.115701       1.267
1       10021   A       AC      -0.117355       1.253
1       10027   A       AC      -0.114670       1.275
1       10033   A       AC      -0.098175       1.423
1       10039   A       AC      -0.098341       1.422
1       10045   A       AC      -0.098460       1.421
1       10049   TA      T       -0.106227       1.349
1       10054   C       CTT     -0.102631       1.382
```

Output:
```
##fileformat=VCFv4.2
##source=CADD_GRCh37-v1.6
##reference=GRCh37
##INFO=<ID=RawScore,Number=1,Type=Float,Description="Raw CADD score">
##INFO=<ID=PHRED,Number=1,Type=Float,Description="CADD PHRED-like score">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       10001   .       T       TC      .       .       RawScore=-0.115832;PHRED=1.266
1       10009   .       A       AC      .       .       RawScore=-0.115586;PHRED=1.268
1       10012   .       C       CT      .       .       RawScore=-0.116324;PHRED=1.261
1       10013   .       T       TA      .       .       RawScore=-0.116117;PHRED=1.263
1       10015   .       A       AC      .       .       RawScore=-0.115701;PHRED=1.267
1       10021   .       A       AC      .       .       RawScore=-0.117355;PHRED=1.253
1       10027   .       A       AC      .       .       RawScore=-0.114670;PHRED=1.275
1       10033   .       A       AC      .       .       RawScore=-0.098175;PHRED=1.423
1       10039   .       A       AC      .       .       RawScore=-0.098341;PHRED=1.422
1       10045   .       A       AC      .       .       RawScore=-0.098460;PHRED=1.421
1       10049   .       TA      T       .       .       RawScore=-0.106227;PHRED=1.349
1       10054   .       C       CTT     .       .       RawScore=-0.102631;PHRED=1.382
```

The script also validates the CADD Indel header, extracts genome and
version, and if an unexpected header found, errors as follows:

```sh
Error: Invalid header line or reference genome and CADD version not found.
Error: Unable to extract reference genome and CADD version.
```